In [1]:
# import the libaray
import pandas as pd
import numpy as np

In [2]:
# import Series and DataFrame into the local namespace
from pandas import Series, DataFrame

## 5.1 Introduction to pandas Data Structures
### Series
A Series is a one-dimensional array-like object with associated array of data labels, called its index.

In [3]:
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj2 = pd.Series([4,-7,-5,3],index = ['d','b','a','c'])
obj2

d    4
b   -7
a   -5
c    3
dtype: int64

In [7]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [8]:
obj2.values

array([ 4, -7, -5,  3], dtype=int64)

In [9]:
# selecting values
# using label
obj2['a']

-5

In [10]:
# operate as array or list
obj2[2]

-5

In [11]:
obj2[['a','b','c']]

a   -5
b   -7
c    3
dtype: int64

In [12]:
obj2[[1,2,3]]

b   -7
a   -5
c    3
dtype: int64

In [13]:
# filtering with a boolean array
obj2[obj2>0]

d    4
c    3
dtype: int64

In [14]:
obj[:2]

0    4
1    7
dtype: int64

In [15]:
obj2*2

d     8
b   -14
a   -10
c     6
dtype: int64

In [16]:
np.exp(obj2)

d    54.598150
b     0.000912
a     0.006738
c    20.085537
dtype: float64

In [17]:
'b' in obj2

True

In [18]:
3 in obj2

False

In [19]:
# create a Series from the dict
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [20]:
# override dict's keys by passing the dict keys
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index = states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [21]:
# detect missing data
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [22]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [23]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [24]:
# automatically aligns by index label
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [25]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [26]:
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [27]:
# Both the Series object itself and its index have a name attribute
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [28]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [29]:
# A Series’s index can be altered in-place by assignment:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [30]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### DataFrame
 The DataFrame has both a row and column index; 

In [31]:
# Construct a DataFrame by a dict of equal-length lists or NumPy arrays
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [32]:
# For large DataFrames, the head method selects only the first five rows
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [33]:
# Rearrange columns
pd.DataFrame(data, columns = ['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [34]:
# If you pass a column that isn’t contained in the dict, it will appear with missing values in the result:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], \
                             index=['one', 'two', 'three', 'four', \
                                  'five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [35]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [36]:
frame2.index

Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')

In [37]:
# a column in a DataFrame can be retrieved as a Series  either by dict-like notation or by attribute
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [38]:
frame.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [39]:
# rows can also be retrieved by position or name with the special loc attributes
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [40]:
frame2.loc['one':'three']

year state  pop debt
one    2000  Ohio  1.5  NaN
two    2001  Ohio  1.7  NaN
three  2002  Ohio  3.6  NaN

In [41]:
# Columns can be modified by assignment
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [42]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [43]:
'''
when you are assigning lists or arrays to a column, the value's lengh must match
the length of the DataFrame. 

If you assign a Series, its labels will realigned exactly to the DataFrame's index, inserting
missing values in any holes
'''

val = pd.Series([-1.2,-1.5,-1.7], index=['two','four','five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [44]:
# Assigning a column that doesn’t exist will create a new column.
frame2['eastern'] = frame2.state=='Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [45]:
# the del method can be used to remove this column
del frame2['eastern']
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [46]:
'''
Another common form of data is a nested dict of dicts
pandas will interpret the outer dict keys as the columns and the inner keys as the row indices
'''
pop = {'Nevada': {2001: 2.4, 2002: 2.9},'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [47]:
# transpose the DataFrame with similar syntax to a NumPy array
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [48]:
# If a DataFrame's index and columns have their name attributes set, these will
# also be displayed
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [49]:
# As with Series, the values attribute returns the data contained in the DataFrame as a 
# two-dimensional ndarray:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [50]:
# If the DataFrame's columns are different dtypes, the dtype of the values array will be chosen to accommodate all of the columns:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

 Possible data inputs to DataFrame constructor
 ![ Possible data inputs to DataFrame constructor](./figs/5-1.jpg)

### Index Objects

In [51]:
obj = pd.Series(range(3),index=['a','b','c'])
obj.index

Index(['a', 'b', 'c'], dtype='object')

In [52]:
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [53]:
index[1:]

Index(['b', 'c'], dtype='object')

In [54]:
# index[1] = 'd'  # error, index objets are immutable

In [55]:
# Immutability makes it safer to share Index objects among data structures:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [56]:
obj2 = pd.Series([1.5,-2.5,0], index = labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [57]:
obj2.index is labels

True

In [58]:
# In addition to being array-like, an Index also behaves like a fixed-size set
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [59]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [60]:
'Ohio' in frame3.columns

True

In [61]:
2003 in frame3.index

False

In [62]:
# Unlike Python sets, a pandas Index can contain duplicate labels:
dup_labels = pd.Index(['foo','foo','bar','bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

Some Index methods and properties
![Some Index methods and properties](./figs/5-2.jpg)