>如果需要使用其他notebook内的函数，则可以通过notebook的run命令先运行其他notebook  
%run KNN.ipynb

## NumPy 基础
numpy（Numerical Python）是用于同类型的多维数组，可用一个正数的元组对其元素进行索引。在NumPy中dimensions也被称作axes。  
例如，一个三维空间的坐标为`[1, 2, 3]`是一维数组包含三个元素，所以我们说他的长度为三。在下面的例子中，这个数组有两个aexs，第一axis长度为2，第二axis长度为3.  
`[[1, 0, 0],
  [0, 2, 3]]`

NumPy的类名称为 `ndarray`。同时也被他的别名 `array`所熟知。注意`numpy.array`不同与Python标准库的`array.array`,标准库的`array`仅处理一维数组以及提供较少的功能。对于`ndarray`比较重要的属性为：  
- **ndarray.ndim**  
返回数组维数的数量，例如对于二维数组，返回2，三维数组相应返回3。

- **ndarray.shape**  
返回数组维数的元组。例如对于`n*m`的数组，返回元组为 `(n,m)`。

- **ndarray.size**  
返回数组中元素的个数，等于`ndarray.shape` 中元素的乘积。

- **ndarray.dtype**  
返回数组中元素的类型。  
- **ndarray.itemsize**  
返回数组中每个元素的字节长度。相当于`ndarray.dtype.itemsize.`
- **ndarray.data**  
返回数组中包含的元素。一般情况下我们将不会用这个属性，因为我们可以通过索引对数组中的数据直接进行访问。

In [1]:
# 导入numpy库
import numpy as np;
# 此函数可以创建一个数值从0到14的数组
a = np.arange(15);
print("a = ",a)

a =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [2]:
# reshape可用于对数组的维数重新分配
b = a.reshape(3,5);
print("b = ",b);

b =  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [3]:
# 返回数组的大小
b.shape

(3, 5)

In [4]:
#返回是几维数组
b.ndim

2

In [5]:
#返回数组中元素的数据类型
b.dtype.name

'int64'

In [6]:
# 返回数组中元素所占的字节数
b.itemsize

8

In [7]:
#返回数组中元素的个数
b.size

15

In [8]:
#返回b的类型
type(b)

numpy.ndarray

In [9]:
# 创建一个数组，数组的元素为6,7,8
c = np.array([6,7,8])
c

array([6, 7, 8])

In [10]:
# 用构造函数创建数组，[3,4]参数表示数组的维数
d = np.ndarray([3,4])
d

array([[4.64382377e-310, 1.78571125e-051, 5.01163191e+217,
        5.49419094e-143],
       [1.44297281e+214, 4.76488706e+180, 1.47763641e+248,
        1.16096346e-028],
       [4.50620322e-144, 7.79952704e-143, 1.69218443e-052,
        5.55290930e+170]])

### 创建数组的几种方法

例如，可以用Python中的list列表或者tuple元数组作为array函数的输入，来创建一个数组。 创建数组的数组类型与输入参数的元素的数据类型有关。

In [11]:
import numpy as np
# 注意[2,3,4] 在Python中表示一个list
print(type([2,3,4]))
# 将[2,3,4]这个list作为函数array的参数，将其转换为数组。
# 一个比较常见的错误就是在括号中只输入数值，而没有添加方括号。
a = np.array([2,3,4]);
print(type(a));
print(a);
print(a.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[2 3 4]
int64


In [12]:
import numpy as np
# 创建二维数组的方法
b = np.array([(1,2,3),(4,5,6)]);
print(type(b));
b

<class 'numpy.ndarray'>


array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
import numpy as np
# 在创建数组的时候也可以指定数据类型
c = np.array([(1,2,3),(4,5,6)], dtype = complex);
print(c)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [14]:
# 在创建数组的时候可以对数组直接进行初始化为0，1，或者是未初始化状态
import numpy as np;
print("zeros = \n",np.zeros((3,4)));
print("ones = \n",np.ones((2,3),dtype=np.int16));
# uninitialize
print("empty = \n", np.empty((2,3)));

zeros = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones = 
 [[1 1 1]
 [1 1 1]]
empty = 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
# 利用arange生成序列
import numpy as np;
#参数分别表示数据的起始，结束和步长。 注意结束的数据不包含在内。
print(np.arange(10,30,5));
#参数表示数据的结束，默认是从0开始，步长是1。
print(np.arange(5));
#此函数也接受浮点参数
print(np.arange(0,4,1.2));

[10 15 20 25]
[0 1 2 3 4]
[0.  1.2 2.4 3.6]


In [16]:
#使用arange函数生成浮点序列时，通常无法预测生成数据的个数
#此种情况下可使用linspace函数
import numpy as np;
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [17]:
import numpy as np;
np.linspace(0,8,9)

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [18]:
import numpy;
from numpy import pi;
x = np.linspace(0,2*pi,100);
f = np.sin(x);

### 数组的运算

In [19]:
import numpy;
#矩阵运算
# * 表示直接相乘，@ means doc product
A = np.array(np.arange(10,20,4));
B = np.array(np.arange(3));
print(A);
print(B);
#数组的加法
print(A+B);
#数组的元素之间的乘法
print(A*B);
#矩阵运算的点乘
print(A@B)

[10 14 18]
[0 1 2]
[10 15 20]
[ 0 14 36]
50


### Matrix

In [20]:
import numpy as np
xMat = np.mat([[1, 2, 3], [2, 3, 4]])
print(xMat)
print(type(xMat))

[[1 2 3]
 [2 3 4]]
<class 'numpy.matrixlib.defmatrix.matrix'>


### 矩阵的数据类型永远是二维的，没有一维矩阵

In [21]:
print(xMat[0, :])
print(type(xMat[0, :]))
print(xMat[:, 0])
print(type(xMat[:, 0]))

[[1 2 3]]
<class 'numpy.matrixlib.defmatrix.matrix'>
[[1]
 [2]]
<class 'numpy.matrixlib.defmatrix.matrix'>


In [22]:
print(type(xMat.A)) # 将matrix转换为ndarray类型

<class 'numpy.ndarray'>
