In [1]:
import numpy as np
np.random.rand(4,4)

array([[0.40124335, 0.29049806, 0.64427591, 0.08405139],
       [0.48826633, 0.9396359 , 0.00544124, 0.70815429],
       [0.98554753, 0.17497474, 0.11487021, 0.15487624],
       [0.59237768, 0.44520183, 0.36968632, 0.63545267]])

- An array can be converted to a matrix by calling the mat() function;

In [2]:
randmat = np.mat(np.random.rand(4,4))
print(randmat)

[[0.35896938 0.18197187 0.9835725  0.32262575]
 [0.71702874 0.38808721 0.62538637 0.8735926 ]
 [0.60654032 0.04742193 0.61978227 0.70165422]
 [0.03447854 0.59034144 0.09147859 0.35907997]]


- the `.I` opertator solves the inverse of a matrix

In [3]:
randmat.I

matrix([[ 0.15771586,  7.97615474, -7.60766269, -4.68097487],
        [ 0.58677204,  3.22823965, -4.14788404, -0.27596549],
        [ 1.27884216, -1.65442665,  1.1648438 ,  0.59983826],
        [-1.30561545, -5.65173612,  7.25301031,  3.53524233]])

In [4]:
invRandmat = randmat.I

In [5]:
randmat*invRandmat

matrix([[ 1.00000000e+00, -2.22044605e-16, -4.44089210e-16,
          0.00000000e+00],
        [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
          0.00000000e+00],
        [ 0.00000000e+00,  4.44089210e-16,  1.00000000e+00,
          0.00000000e+00],
        [-5.55111512e-17,  4.44089210e-16,  8.88178420e-16,
          1.00000000e+00]])