In [11]:
import numpy as np
np.random.rand(4,4)

array([[0.29518938, 0.61611363, 0.86993316, 0.83697696],
       [0.76036566, 0.49954986, 0.38515629, 0.81046675],
       [0.03450358, 0.15873404, 0.04593711, 0.70230105],
       [0.92799412, 0.70251142, 0.17974871, 0.10371283]])

- An array can be converted to a matrix by calling the mat() function;

In [12]:
randmat = np.mat(np.random.rand(4,4))
print(randmat)

[[0.17495028 0.31090829 0.9564161  0.85765893]
 [0.09943432 0.83116311 0.90596632 0.17146808]
 [0.20529859 0.00990231 0.9776193  0.1784301 ]
 [0.37417834 0.68423467 0.77460249 0.40872552]]


- the `.I` opertator solves the inverse of a matrix

In [13]:
randmat.I

matrix([[-1.35947615, -2.40539364,  0.76325201,  3.52859775],
        [-0.16123919,  0.95461516, -1.03602956,  0.39014214],
        [ 0.01636373,  0.58893213,  1.0458342 , -0.73796678],
        [ 1.4834811 , -0.51213556, -0.94638279, -0.03827197]])

In [14]:
invRandmat = randmat.I

In [10]:
randmat*invRandmat

matrix([[ 1.00000000e+00,  5.55111512e-16, -4.44089210e-16,
          1.11022302e-16],
        [ 1.11022302e-16,  1.00000000e+00, -4.44089210e-16,
          0.00000000e+00],
        [ 0.00000000e+00, -1.11022302e-16,  1.00000000e+00,
          0.00000000e+00],
        [ 0.00000000e+00, -1.66533454e-16, -2.22044605e-16,
          1.00000000e+00]])