> A universal function, or ufunc, is a function that performs element-wise operations
on data in ndarrays. You can think of them as fast vectorized wrappers for simple
functions that take one or more scalar values and produce one or more scalar results.

In [1]:
import numpy as np
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [3]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [4]:
x = np.random.randn(8)
y = np.random.randn(8)
print(x)
print(y)

[-0.55413167  0.47965089  1.08762007 -1.88865917 -0.2264193  -0.25091752
 -1.75994883  0.01899395]
[ 1.53200143  1.21150901  1.52596223  0.13220866 -1.19367079  0.61341962
  0.48498076  0.22761914]


In [5]:
np.maximum(x,y)

array([ 1.53200143,  1.21150901,  1.52596223,  0.13220866, -0.2264193 ,
        0.61341962,  0.48498076,  0.22761914])

Here,  numpy.maximum  computed the element-wise maximum of the elements in  x  and y .

In [6]:
# divmod
arr = np.random.randn(7) *5
arr

array([ 4.20391124,  5.30696155,  5.54149772, -2.97809006, -1.35736581,
       -2.30947928,  2.82364774])

In [7]:
remainder, whole_part = np.modf(arr)
remainder

array([ 0.20391124,  0.30696155,  0.54149772, -0.97809006, -0.35736581,
       -0.30947928,  0.82364774])

In [8]:
whole_part

array([ 4.,  5.,  5., -2., -1., -2.,  2.])

In [9]:
# Ufuncs accept an optional out argument that allows them to operate in-place on arrays:
arr

array([ 4.20391124,  5.30696155,  5.54149772, -2.97809006, -1.35736581,
       -2.30947928,  2.82364774])

In [10]:
np.sqrt(arr,arr)
arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([2.05034418, 2.30368434, 2.3540386 ,        nan,        nan,
              nan, 1.68037131])

Unary ufuncs
![](./figs/4-3.jpg)

![](./figs/4-4.jpg)