As a simple example, suppose we wished to evaluate the function  sqrt(x^2 + y^2) 
across a regular grid of values. The  np.meshgrid  function takes two 1D arrays and
produces two 2D matrices corresponding to all pairs of  (x, y)  in the two arrays:

In [1]:
import numpy as np
points = np.arange(-5,5,0.01) # 1000 equally spaced points
xs, ys = np.meshgrid(points, points)
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [2]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [3]:
z = np.sqrt(xs ** 2 + ys ** 2)
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

In [4]:
#matplotlib inline
import matplotlib.pyplot as plt
plt.imshow(z, cmap=plt.cm.gray); plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")
plt.show()

<Figure size 640x480 with 2 Axes>

### Expressing Conditional Logic as Array Operations

In [5]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
# suppose we want to take a value from xarr whenever the condition is true, and otherwise take the value from yarr.
result = [(x if c else y) for x, y , c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [6]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [7]:
# suppose we want to set all positive values with 2 and all negative values with -2.
arr = np.random.randn(4,4)
arr

array([[ 0.66513615,  0.49040327,  0.96579341,  0.59647587],
       [ 0.35633396,  0.27659249,  1.67609595, -1.03313032],
       [-0.92397851,  0.07094773, -1.03571635,  0.17429055],
       [-0.36810954,  1.72110901, -0.93374687, -0.71421739]])

In [8]:
arr>0

array([[ True,  True,  True,  True],
       [ True,  True,  True, False],
       [False,  True, False,  True],
       [False,  True, False, False]])

In [9]:
arr[arr>0] = 2
arr[~(arr>0)] = -2
arr

array([[ 2.,  2.,  2.,  2.],
       [ 2.,  2.,  2., -2.],
       [-2.,  2., -2.,  2.],
       [-2.,  2., -2., -2.]])

In [10]:
arr = np.random.randn(4,4)
arr

array([[-0.48567504,  3.25478011,  0.35210855, -0.83780967],
       [-0.75031186, -2.38243505,  1.3737291 ,  0.25742713],
       [ 1.73091717,  0.46779417,  0.88146504, -0.09455647],
       [-0.45018029, -0.59817228,  1.67962783, -0.41298803]])

In [11]:
np.where(arr>0, 2, -2)

array([[-2,  2,  2, -2],
       [-2, -2,  2,  2],
       [ 2,  2,  2, -2],
       [-2, -2,  2, -2]])

In [12]:
# replace all positive values in arr with constant 2
np.where(arr>0,2,arr)

array([[-0.48567504,  2.        ,  2.        , -0.83780967],
       [-0.75031186, -2.38243505,  2.        ,  2.        ],
       [ 2.        ,  2.        ,  2.        , -0.09455647],
       [-0.45018029, -0.59817228,  2.        , -0.41298803]])

### Mathematical and Statistical Methods

In [13]:
# compute some aggregate statistics
arr = np.random.randn(5,4)
arr

array([[ 2.61611533, -1.45225299,  0.14577702, -1.94902333],
       [ 0.21876252,  0.01140639,  2.1373709 ,  0.03837114],
       [-1.51811569, -0.01016245, -0.98369108,  0.46113412],
       [ 0.29216197,  1.26102228, -2.39700005, -1.42738848],
       [ 0.07622096, -0.80726079,  0.71882016, -0.38882986]])

In [14]:
arr.mean()

-0.1478280970828713

In [15]:
np.mean(arr)

-0.1478280970828713

In [16]:
arr.sum()

-2.9565619416574265

In [17]:
arr.mean(axis=1) # compute mean across the columns

array([-0.15984599,  0.60147774, -0.51270878, -0.56780107, -0.10026238])

In [18]:
arr.sum(axis=0) # compute sum down the rows

array([ 1.68514509, -0.99724755, -0.37872306, -3.26573642])

In [19]:
# other methods like cumsum and cumprob do not aggregate
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [20]:
# multidimensional
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [22]:
arr.cumsum(axis=1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]], dtype=int32)

![basic array](./figs/4-5.jpg)

### Methods for Boolean Arrays

In [23]:
arr = np.random.randn(100)
(arr>0).sum() # number of positive values

53

In [24]:
bools = np.array([False, False, True, False])
bools.any()

True

In [25]:
bools.all()

False

### Sorting

In [26]:
# NumPy arrays can be sorted in place with sort method
arr = np.random.randn(6)
arr

array([-0.21740693, -0.81563497,  0.22738364,  0.38109501,  1.1076372 ,
       -0.66639336])

In [27]:
arr.sort()
arr

array([-0.81563497, -0.66639336, -0.21740693,  0.22738364,  0.38109501,
        1.1076372 ])

In [28]:
arr = np.random.randn(5,3)
arr

array([[ 0.50950808, -1.35807578,  1.71316916],
       [ 0.94197431, -0.91228304, -0.79166752],
       [-1.42224785,  1.92789118, -0.08155459],
       [-0.50031956,  1.16537278,  1.118906  ],
       [ 0.08629687,  0.38663565,  0.70060594]])

In [29]:
arr.sort(1)
arr

array([[-1.35807578,  0.50950808,  1.71316916],
       [-0.91228304, -0.79166752,  0.94197431],
       [-1.42224785, -0.08155459,  1.92789118],
       [-0.50031956,  1.118906  ,  1.16537278],
       [ 0.08629687,  0.38663565,  0.70060594]])

In [30]:
arr.sort(0)
arr

array([[-1.42224785, -0.79166752,  0.70060594],
       [-1.35807578, -0.08155459,  0.94197431],
       [-0.91228304,  0.38663565,  1.16537278],
       [-0.50031956,  0.50950808,  1.71316916],
       [ 0.08629687,  1.118906  ,  1.92789118]])

In [31]:
# the top-level method np.sort returns a sorted copy of an array instead of modifying the array in-place
arr = np.random.randn(4,3)
arr

array([[-1.59368465, -0.0396025 , -0.85736884],
       [-0.10176274,  1.75710249,  0.09522596],
       [-0.25131052, -0.97252384,  0.45121   ],
       [ 1.9853399 , -0.28958477,  1.31731322]])

In [32]:
np.sort(arr)

array([[-1.59368465, -0.85736884, -0.0396025 ],
       [-0.10176274,  0.09522596,  1.75710249],
       [-0.97252384, -0.25131052,  0.45121   ],
       [-0.28958477,  1.31731322,  1.9853399 ]])

In [33]:
arr

array([[-1.59368465, -0.0396025 , -0.85736884],
       [-0.10176274,  1.75710249,  0.09522596],
       [-0.25131052, -0.97252384,  0.45121   ],
       [ 1.9853399 , -0.28958477,  1.31731322]])

In [34]:
'''
A quick-and-dirty way to compute the quantiles of an array is to
sort it and select the value at a particular rank:
'''
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05*len(large_arr))] # 5% quantile


-1.669666732521485

### Unique and Other Set Logic

In [35]:
# np.unique returns the sorted unique values in an array
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [36]:
ints = np.array([3,3,3,2,2,1,1,4,4])
np.unique(ints)

array([1, 2, 3, 4])

In [37]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [38]:
# np.in1d, tests membership of the values in one array in another
values = np.array([6,0,0,3,2,5,6])
np.in1d(values, [2,3,6])

array([ True, False, False,  True,  True, False,  True])

![array set operations](./figs/4-6.jpg)