In [1]:
import numpy as np
x = np.array([[1., 2., 3.],[4., 5., 6.]])
y = np.array([[6., 23.],[-1., 7],[8., 9.]])
print(x)

[[1. 2. 3.]
 [4. 5. 6.]]


In [2]:
print(y)

[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]


In [3]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [4]:
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [5]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [6]:
# @ also work for matrix multiplication
x @ np.ones(3)

array([ 6., 15.])

In [7]:
'''
numpy.linalg   has  a  standard  set  of  matrix  decompositions  and  things  like  inverse
and  determinant. 
'''
from numpy.linalg import inv, qr

In [8]:
x = np.random.randn(5,5)
mat = x.T.dot(x)

In [9]:
inv(mat)

array([[ 1.26797137, -0.06497884, -0.63632911,  0.32473442, -0.17017077],
       [-0.06497884,  0.11273293, -0.00258972,  0.02078107, -0.04256648],
       [-0.63632911, -0.00258972,  0.65038813, -0.26181608,  0.14484052],
       [ 0.32473442,  0.02078107, -0.26181608,  0.35798265, -0.10427068],
       [-0.17017077, -0.04256648,  0.14484052, -0.10427068,  0.14012039]])

mat.dot(inv(mat))

In [11]:
q,r = qr(mat)

In [12]:
q

array([[-0.62459234,  0.40727085,  0.28721015, -0.09732418, -0.59334071],
       [-0.51230913, -0.77617065, -0.24044069,  0.23507193, -0.14841813],
       [-0.48421256,  0.41026787, -0.58460407,  0.02026191,  0.5050208 ],
       [ 0.155379  , -0.09252319, -0.53341734, -0.74201326, -0.36356442],
       [-0.29802573, -0.23411388,  0.4831176 , -0.61989916,  0.48856296]])

In [13]:
r

array([[-2.86217024, -8.44256655, -2.21096922,  0.24273991, -5.70156273],
       [ 0.        , -9.34721064,  2.01145157, -0.20951366, -6.74546762],
       [ 0.        ,  0.        , -2.83507129, -2.17768227,  4.75792557],
       [ 0.        ,  0.        ,  0.        , -4.29157051, -7.61762148],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  3.486737  ]])

![](./figs/4-7.jpg)