In [1]:
# standard normal distribution
import numpy as np
samples = np.random.normal(size=(4,4))
print(samples)

[[-0.06637729  1.25024178 -0.61283906  0.94650752]
 [-0.40385274  0.20153767 -1.86519397 -0.05582097]
 [ 2.10878716 -0.81741684  0.02041538 -0.27464963]
 [ 0.59694076  1.17820228 -0.21917156 -2.1736246 ]]


In [2]:
# build-in random module only samples one value at time
from random import normalvariate
N = 1000000
%timeit samples = [normalvariate(0, 1) for _ in range(N)]
%timeit np.random.normal(size=N)

1.27 s ± 29.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
43.2 ms ± 944 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [3]:
# set the seed, this will influence all random functions, global setting
np.random.seed(1234)
print(np.random.randn(10))
print(np.random.randn(10))
print(np.random.randn(10))

[ 0.47143516 -1.19097569  1.43270697 -0.3126519  -0.72058873  0.88716294
  0.85958841 -0.6365235   0.01569637 -2.24268495]
[ 1.15003572  0.99194602  0.95332413 -2.02125482 -0.33407737  0.00211836
  0.40545341  0.28909194  1.32115819 -1.54690555]
[-0.20264632 -0.65596934  0.19342138  0.55343891  1.31815155 -0.46930528
  0.67555409 -1.81702723 -0.18310854  1.05896919]


In [4]:
# isolated
rng = np.random.RandomState(1234)
print(rng.randn(10))

[ 0.47143516 -1.19097569  1.43270697 -0.3126519  -0.72058873  0.88716294
  0.85958841 -0.6365235   0.01569637 -2.24268495]


![](./figs/4-8.jpg)