# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
print(np.show_config())

1.16.4
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib'

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [4]:
print(np.size(a))

10


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
print(np.info("add"))

     *** Found in numpy ***
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
a = np.zeros(10)
a[5]=1
print(a)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
a = np.arange(10,49)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [8]:
a = np.arange(10)
print(a)
print(a[::-1])

# convert to list
print(a.tolist())
print([ i for i in reversed(a)]) # output is list

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
print(np.arange(0,9).reshape((3,3)))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [10]:
a = [1,2,0,0,4,0]
arr = np.array(a)
print(arr>0)
print(arr[arr>0])

[ True  True False False  True False]
[1 2 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
print(np.random.random((3,3)))

[[0.77372063 0.46104018 0.56678049]
 [0.70345095 0.63276601 0.76600583]
 [0.04610039 0.26514734 0.94048219]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
rand33 = np.random.random((10,10))
print(rand33)
print(np.min(rand33))
print(np.max(rand33))

[[0.03256927 0.04221456 0.45234279 0.03146771 0.31596519 0.01206756
  0.16885931 0.094395   0.51964419 0.19457298]
 [0.97401299 0.64513306 0.66560401 0.44717696 0.91008177 0.22181135
  0.52698247 0.01134293 0.01317188 0.25480797]
 [0.95394411 0.60763782 0.56668902 0.89865329 0.78684045 0.22066113
  0.44775226 0.17459177 0.66977087 0.49614714]
 [0.292768   0.81454574 0.23388338 0.16535092 0.36665502 0.25636423
  0.60213303 0.46985293 0.8198512  0.63420165]
 [0.82062038 0.39916326 0.36588163 0.18432349 0.92858217 0.24047276
  0.76503389 0.40585139 0.08330311 0.57859225]
 [0.85165152 0.01246075 0.86371675 0.73974859 0.5817013  0.23530432
  0.90449301 0.49882337 0.01401902 0.92735692]
 [0.09956909 0.87567671 0.6872833  0.56631694 0.24305359 0.26480316
  0.38323535 0.97057312 0.71638717 0.9651792 ]
 [0.51379371 0.4390855  0.36974399 0.01428609 0.77728905 0.40163453
  0.33811215 0.46626144 0.21297341 0.94069449]
 [0.7574136  0.04082198 0.50954621 0.46931888 0.27392657 0.06406392
  0.99962723

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
print(np.mean(np.random.random(30)))

0.5425437694019198


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
arr = np.ones((5,6))
print(arr)
arr[1:-1,1:-1]=0
print(arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
arr = np.random.random((3,4))
print(arr)
print(np.pad(arr,pad_width=1,mode="constant"))

[[0.62111216 0.88734211 0.96333029 0.73995574]
 [0.14737697 0.87569784 0.12349813 0.69928828]
 [0.92452753 0.44032273 0.2917591  0.07389153]]
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.62111216 0.88734211 0.96333029 0.73995574 0.        ]
 [0.         0.14737697 0.87569784 0.12349813 0.69928828 0.        ]
 [0.         0.92452753 0.44032273 0.2917591  0.07389153 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

- nan
- False
- False
- nan
- True
- False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [17]:
print(np.diag((1,2,3,4),k=-1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [18]:
# x[startAt:endBefore:skip]
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [19]:
print(np.floor(99/7/8))
print(np.floor((99-1*7*8)/8))
print(np.floor(99-1*7*8-5*8))

print(np.unravel_index(99,(6,7,8)))

1.0
5.0
3.0
(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [20]:
print(np.tile([[0,1],[1,0]], (4,4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [21]:
Z=np.random.randn(5,5)
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 1.14230672 -0.02296437 -1.8088444  -0.88143564  0.91755399]
 [ 0.68865306 -1.35743955 -2.26789201  0.85085719  0.02130703]
 [-0.4664142  -0.32591069  0.22801345 -0.73773714  0.16191953]
 [-0.50175067  0.90011266  1.59765649  0.90906151  0.78082261]
 [ 0.77172428  1.30973137 -1.45867839 -0.4280818  -0.02257105]]


In [22]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-1.02382241  1.21725925  0.64846572 -1.31827862 -0.66588761]
 [ 0.7275136   0.57634394 -1.29663296 -0.18325284  1.28072766]
 [-2.01456191 -1.01837039 -0.16707113  0.41005068 -0.1811317 ]
 [ 1.32026342  0.44268661  0.63840461 -1.18709733  1.44632457]
 [ 0.83165363  0.28056891  1.27352565 -0.94349296 -1.09418838]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [23]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:
a = np.random.randn(5,3)
b = np.random.randn(3,2)
a.dot(b)

array([[-3.75576225,  0.60619471],
       [ 0.51166858, -0.48043074],
       [ 2.10079721,  0.51815502],
       [ 0.60029767, -0.60297628],
       [-1.84293873,  0.10364174]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [25]:
arr = np.random.random(10)*10
arr[(arr>3) & (arr<8)] *=-1
arr

array([ 9.14583205,  0.02662784, -3.51570024, -7.201881  ,  8.38400214,
       -6.32651202, -4.4273011 ,  9.47739858,  1.66835823,  8.66542194])

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
a = [i for i in range(5)]
print(a)
help(sum)
help(np.sum)
print(sum(range(5),-1))
print(np.sum(range(5),-1))

[0, 1, 2, 3, 4]
Help on built-in function sum in module builtins:

sum(iterable, start=0, /)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers
    
    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.

Help on function sum in module numpy:

sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>)
    Sum of array elements over a given axis.
    
    Parameters
    ----------
    a : array_like
        Elements to sum.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a sum is performed.  The default,
        axis=None, will sum all of the elements of the input array.  If
        axis is negative it counts from the last to the first axis.
    
        .. versionadded:: 1.7.0
    
        If axis is a tuple of ints, a sum is performed on all of the axes
        specified in the tuple instead o

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [27]:
Z = np.arange(5)
print(Z)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
# print(Z<Z>Z) # error

[0 1 2 3 4]
[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [28]:
print(np.array(0)/np.array(0))
print(np.array(0)//np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆)

In [29]:
Z = np.random.uniform(-10,+10,10)
print(Z)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ 3.22152193  5.05842147 -3.11108628  8.79980042  5.59325922  9.91511279
  1.6557665  -8.97832109 -4.79323509  3.10745441]
[ 4.  6. -4.  9.  6. 10.  2. -9. -5.  4.]


#### 30. How to find common values between two arrays? (★☆☆)

In [30]:
a = np.arange(5,10)
b = np.arange(8,15)
print(a)
print(b)
print(set(a) & set(b)) # set operation
print(np.intersect1d(a,b))

[5 6 7 8 9]
[ 8  9 10 11 12 13 14]
{8, 9}
[8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [31]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [32]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [33]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

2019-06-22
2019-06-23
2019-06-24


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [34]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [35]:
A = np.arange(1,10)
B = np.arange(11,20)
B = A + B
A = -A/2
print(B*A)

[  -6.  -14.  -24.  -36.  -50.  -66.  -84. -104. -126.]


In [36]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [37]:
arr = np.random.random(10)*10
print(arr)

print(np.floor(arr))

print(list(map(int, arr)))

print(arr.astype(int))

print(arr - arr%1)

print(np.ceil(arr)-1)

[2.85296684 2.56671832 7.4399406  9.01812512 5.01517947 1.64917803
 8.53731558 0.10511497 8.41208422 0.2430635 ]
[2. 2. 7. 9. 5. 1. 8. 0. 8. 0.]
[2, 2, 7, 9, 5, 1, 8, 0, 8, 0]
[2 2 7 9 5 1 8 0 8 0]
[2. 2. 7. 9. 5. 1. 8. 0. 8. 0.]
[2. 2. 7. 9. 5. 1. 8. 0. 8. 0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [38]:
print(np.tile(range(5),(5,1)))

Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [39]:
def generator():
    for i in range(10):
        yield(i)

x = generator()
print([i for i in x])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [40]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [41]:
print(np.linspace(0,1,11, endpoint=False)[1:])

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [42]:
print(np.sort(np.random.random(10)))

[0.03049307 0.0912905  0.18548643 0.29508213 0.37146616 0.44614929
 0.47763051 0.61504848 0.93285013 0.9354851 ]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [43]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [44]:
A = np.random.random(10)
B = np.random.random(10)
print(np.all(A==B))

equal = np.array_equal(A,B)
print(equal)


False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [45]:
Z = np.zeros(10)
Z.flags.writeable = False
# Z[1]=10 # error assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [46]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.82262194 0.93987937 0.70984017 1.1543933  0.03412758 0.98833938
 0.43045617 0.30316842 0.65500471 0.5896513 ]
[1.07768032 0.92886546 1.1780632  0.98230698 0.90222495 0.31333152
 0.87610829 0.29676544 1.28268888 0.54063573]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [47]:
A = np.random.random(10)
A[np.argmax(A)] = 0
print(A)

[0.67050602 0.77736881 0.64863301 0.364259   0.29938234 0.
 0.73554396 0.77743511 0.15974527 0.46989185]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [48]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)


[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [49]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))


3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [50]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [51]:
import sys
np.set_printoptions(threshold=sys.maxsize)
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [52]:
A = np.random.random(100)*100
A[np.argmin(np.abs(56-A))]

56.686211539919206

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [53]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)


[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [54]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)


[[0.         0.59007644 0.39465278 0.17022149 0.32570392 0.30388273
  0.37970679 0.59074696 0.52847575 0.55468094]
 [0.59007644 0.         0.19620029 0.48332307 0.88876315 0.55542304
  0.85227072 1.04002496 0.54724577 1.13546979]
 [0.39465278 0.19620029 0.         0.30358934 0.69399718 0.40975674
  0.68232186 0.88077567 0.47815194 0.94381415]
 [0.17022149 0.48332307 0.30358934 0.         0.49199185 0.16376086
  0.37984123 0.58298422 0.36551824 0.65871598]
 [0.32570392 0.88876315 0.69399718 0.49199185 0.         0.59310633
  0.49020656 0.65286327 0.82835479 0.39102704]
 [0.30388273 0.55542304 0.40975674 0.16376086 0.59310633 0.
  0.31289784 0.48555574 0.23546733 0.66410781]
 [0.37970679 0.85227072 0.68232186 0.37984123 0.49020656 0.31289784
  0.         0.21168018 0.49250845 0.38518194]
 [0.59074696 1.04002496 0.88077567 0.58298422 0.65286327 0.48555574
  0.21168018 0.         0.60526812 0.41109366]
 [0.52847575 0.54724577 0.47815194 0.36551824 0.82835479 0.23546733
  0.49250845 0.60526

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [55]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [56]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [57]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [58]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [59]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [60]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
#Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)


[[ 0.33002779  0.48290225  0.04517106  0.46063508  0.10206548 -0.05970954
  -0.27823535 -0.39224757 -0.35894009 -0.3316691 ]
 [-0.14575838  0.42358884 -0.31299034  0.15015348  0.02238006 -0.41388865
   0.42683467  0.2639653  -0.38004485 -0.03424014]
 [ 0.54766289 -0.0551961  -0.36753016  0.25079468 -0.21058802 -0.28257451
   0.01801032 -0.19108834  0.07140264  0.21910658]
 [-0.35101102  0.04550934  0.40400338  0.22705054 -0.09751241 -0.38572453
  -0.03560988  0.3009972   0.21775385 -0.32545648]
 [ 0.36395627  0.37528344  0.30145728 -0.17279038 -0.0016224  -0.39010263
   0.38812441 -0.26257907 -0.14948021 -0.4522467 ]]


#### 59. How to sort an array by the nth column? (★★☆)

In [61]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[1 0 8]
 [0 9 3]
 [1 8 4]]
[[1 0 8]
 [1 8 4]
 [0 9 3]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [62]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [63]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.48954267109726946


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [64]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [65]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")
Z = NamedArray(np.arange(10),"range10")
print(Z)
print(Z.name)

[0 1 2 3 4 5 6 7 8 9]
range10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [66]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(I)
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)

[1 2 0 1 2 0 4 7 7 9 9 5 5 0 8 9 2 4 1 4]
[4. 4. 4. 1. 4. 3. 1. 3. 2. 4.]
[7. 7. 7. 1. 7. 5. 1. 5. 3. 7.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [67]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [68]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [69]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[57 72 56 63]
 [50 38 59 59]
 [64 59 56 67]]
[[57 72 56 63]
 [50 38 59 59]
 [64 59 56 67]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [70]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.51909572 0.56526172 0.62152302 0.62879959 0.5079873  0.31999183
 0.62456323 0.4790271  0.55724576 0.53929143]
0    0.519096
1    0.565262
2    0.621523
3    0.628800
4    0.507987
5    0.319992
6    0.624563
7    0.479027
8    0.557246
9    0.539291
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [71]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version  
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([1.56167264, 1.66565708, 0.99848669, 0.1681031 , 1.00437967])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [72]:
z = np.array([1,2,3,4,5])
nz = 3
z0 = np.zeros(len(z)+nz*(len(z)-1))
z0[::nz+1]=z
print(z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [73]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [74]:
A = np.arange(25).reshape(5,5)
print(A)
A[[0,1]] = A[[1,0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [75]:
A = np.arange(25).reshape(5,5)
print(A)
A[:2,:] = A[1::-1,:]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [76]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1, 37) ( 1, 85) ( 3, 48) ( 3, 94) ( 4, 18) ( 4, 47) ( 5, 27) ( 5, 36)
 (11, 12) (11, 72) (12, 72) (18, 47) (20, 36) (20, 54) (24, 31) (24, 43)
 (27, 36) (31, 43) (36, 41) (36, 54) (36, 60) (37, 85) (41, 60) (48, 94)
 (49, 56) (49, 72) (56, 72) (71, 94) (71, 97) (94, 97)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [77]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [78]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

In [79]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [80]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)
print(Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)
print(Z)

Z = np.random.randint(-5,5,10)
print(-1*Z)

[0 1 1 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 1 0 1 1 1 1 0 0 0 1 1 0 0 0 0 0 0 1 0
 0 1 0 1 0 1 1 0 1 0 0 1 0 0 1 1 1 0 1 1 0 0 0 0 0 0 1 1 1 0 1 1 1 1 1 1 0
 0 0 0 1 1 1 0 1 0 1 0 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0]
[ 6.38416494e-01 -8.15726485e-01 -3.69553819e-01 -9.36094264e-01
  1.60777449e-01 -3.53752788e-01  1.96957023e-01 -8.10837953e-01
  9.94025581e-01  6.27587250e-01  9.21859344e-01 -2.75896444e-01
 -9.84872282e-01  9.25012672e-01  2.57577253e-01  6.48202069e-01
 -9.68855230e-01  2.94355223e-01  7.64144977e-01 -3.15860596e-01
 -2.61493379e-01  2.70744162e-02  1.91012271e-01  7.45266265e-01
  2.43156065e-01  2.28994900e-01  3.34720978e-01  8.04347739e-01
  8.41009777e-01  5.40814602e-01  7.34206956e-01 -3.60918701e-01
 -9.98236648e-01 -1.86845083e-01  7.16094875e-01  8.79309265e-01
  5.97229386e-01  2.22124013e-01 -1.17164414e-01 -6.51652861e-01
 -3.72903349e-04 -1.17322957e-01 -4.93169341e-04  2.63900039e-01
 -7.13733826e-02 -2.86466325e-01  2.54636907e-01  4.70798814e-01
  5.23598576e-01

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [81]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 8.21336556  8.86828732  2.38257001  8.90147554 16.48222149  8.52495706
  4.10333046  7.27501797 10.33062207  4.15977295]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [82]:
# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 1.96063783  1.92285175  6.25605795  1.7222949   0.69419596  5.43062354
   2.15197244  5.07660614  1.60867141 11.40498721]
 [10.48933748  3.83568326 14.31911812  6.81728376  0.90934565 12.50045253
   4.07152566  1.61553574  2.86172855 13.18970156]
 [10.41066261  4.51958455 10.94919607  5.88906961  7.53587344  7.25811935
  12.15135843  5.84704748 11.11353982  4.81557626]
 [ 4.73413456  4.78848984  9.76493721  1.28331747  3.03617456  9.12282594
   0.59721392  5.967799    0.2074525  14.23435458]
 [ 4.66580114 11.38870121  3.31216879  0.4316777  13.33213526  0.96927555
  16.2783173   8.53202537 15.80044067  1.98065472]
 [ 2.45904489  1.96021534  6.69783822  1.23083401  0.63140637  5.797566
   2.33642592  4.80745075  1.75565583 11.43468492]
 [10.90473621  3.79707765 14.65975302  7.2197874   0.78638363 12.76297379
   4.29299697  1.3285139   3.05335837 13.14453916]
 [ 2.67352249  9.55006725  2.33201909  2.19365388 11.06797814  1.20164232
  13.6102599   5.66917348 13.24261823  0.10659991]
 [

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [83]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[2 2 0 5 5 2 9 4 9 9]
 [8 9 0 3 7 8 7 5 5 6]
 [4 6 8 3 9 7 5 1 8 4]
 [0 2 5 9 6 7 7 5 2 2]
 [8 4 3 4 4 7 8 7 8 9]
 [6 2 0 2 4 5 3 0 1 7]
 [8 5 1 4 2 3 6 7 5 6]
 [9 8 8 7 8 3 7 4 3 3]
 [5 7 5 8 4 5 5 6 2 5]
 [0 1 9 3 0 8 3 8 6 2]]
[[0 0 0 0 0]
 [0 2 2 0 5]
 [0 8 9 0 3]
 [0 4 6 8 3]
 [0 0 2 5 9]]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

In [84]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [85]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [86]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [87]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[1 2 1]
   [1 4 2]
   [2 0 1]]

  [[2 1 4]
   [4 2 4]
   [0 1 3]]

  [[1 4 1]
   [2 4 0]
   [1 3 0]]

  [[4 1 4]
   [4 0 3]
   [3 0 3]]

  [[1 4 1]
   [0 3 2]
   [0 3 2]]

  [[4 1 3]
   [3 2 4]
   [3 2 2]]

  [[1 3 1]
   [2 4 0]
   [2 2 4]]

  [[3 1 4]
   [4 0 0]
   [2 4 1]]]


 [[[1 4 2]
   [2 0 1]
   [0 2 0]]

  [[4 2 4]
   [0 1 3]
   [2 0 3]]

  [[2 4 0]
   [1 3 0]
   [0 3 2]]

  [[4 0 3]
   [3 0 3]
   [3 2 4]]

  [[0 3 2]
   [0 3 2]
   [2 4 3]]

  [[3 2 4]
   [3 2 2]
   [4 3 1]]

  [[2 4 0]
   [2 2 4]
   [3 1 0]]

  [[4 0 0]
   [2 4 1]
   [1 0 0]]]


 [[[2 0 1]
   [0 2 0]
   [4 0 3]]

  [[0 1 3]
   [2 0 3]
   [0 3 4]]

  [[1 3 0]
   [0 3 2]
   [3 4 1]]

  [[3 0 3]
   [3 2 4]
   [4 1 2]]

  [[0 3 2]
   [2 4 3]
   [1 2 4]]

  [[3 2 2]
   [4 3 1]
   [2 4 2]]

  [[2 2 4]
   [3 1 0]
   [4 2 4]]

  [[2 4 1]
   [1 0 0]
   [2 4 1]]]


 [[[0 2 0]
   [4 0 3]
   [0 2 3]]

  [[2 0 3]
   [0 3 4]
   [2 3 1]]

  [[0 3 2]
   [3 4 1]
   [3 1 1]]

  [[3 2 4]
   [4 1 2]
   [1 1 4]]

  [[2 4 3]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

In [88]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 7 15 14  9  4]
 [15  3 13 18  9]
 [14 13  4 42 10]
 [ 9 18 42  2 11]
 [ 4  9 10 11  7]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [89]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [90]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [91]:

def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 1 1 1 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
  0 0 1 0 1 1 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0
  0 1 0 0 1 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 0 0 0
  0 0 0 1 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0
  0 0 0 1 1 1 1 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 1 1 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★)

In [92]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9995 9998 9997 9999 9996]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [93]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [94]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [95]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

2.78 s ± 78.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
390 ms ± 31.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
322 ms ± 16.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [96]:

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 2 5 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [97]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[3 4 4]
 [3 2 3]
 [0 2 4]
 [1 1 2]
 [0 4 2]
 [4 4 4]
 [2 2 1]
 [1 0 4]
 [2 2 0]
 [2 1 4]]
[[3 4 4]
 [3 2 3]
 [0 2 4]
 [1 1 2]
 [0 4 2]
 [2 2 1]
 [1 0 4]
 [2 2 0]
 [2 1 4]]
[[3 4 4]
 [3 2 3]
 [0 2 4]
 [1 1 2]
 [0 4 2]
 [2 2 1]
 [1 0 4]
 [2 2 0]
 [2 1 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [98]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [99]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[1 0 1]
 [1 1 1]]
[[1 0 1]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [100]:
# Make sure to read: http://ajcr.net/Basic-guide-to-einsum/

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.16486402, 0.31497471, 0.15680705, 0.29078141, 0.29604728,
        0.43779057, 0.408423  , 0.40232848, 0.16485128, 0.31800431],
       [0.09821377, 0.18763859, 0.09341402, 0.17322602, 0.17636303,
        0.26080318, 0.24330816, 0.2396775 , 0.09820617, 0.1894434 ],
       [0.17162235, 0.32788658, 0.1632351 , 0.30270152, 0.30818325,
        0.45573707, 0.42516563, 0.41882128, 0.17160908, 0.33104037],
       [0.00127748, 0.00244063, 0.00121505, 0.00225317, 0.00229397,
        0.00339229, 0.00316473, 0.00311751, 0.00127738, 0.00246411],
       [0.30337628, 0.57960406, 0.28855016, 0.53508451, 0.54477454,
        0.80560496, 0.75156392, 0.74034903, 0.30335283, 0.585179  ],
       [0.00368161, 0.00703376, 0.00350169, 0.00649349, 0.00661109,
        0.00977638, 0.00912057, 0.00898447, 0.00368132, 0.00710141],
       [0.17730137, 0.33873642, 0.16863659, 0.31271798, 0.3183811 ,
        0.47081751, 0.43923445, 0.43268016, 0.17728766, 0.34199457],
       [0.14814215, 0.28302738, 0.1409023

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [101]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [102]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [103]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)


[-0.23134861  0.16567436]
